file = open('json.txt','r+')
n = input("What is your Name?: ")
c = input("What is your Current CGPA?: ")
b = input("What is your Branch?: ")
u = input("What is your College name: ")
file.write("My Name is ")
file.write(n)
file.write("\n My Current CGPA is ")
file.write(c)
file.write("\n My Branch is ")
file.write(b)
file.write("\n My College name is ")
file.write(u)
file.seek(0)
print(file.read())